---
- name: Check if bootstrap is needed
  raw: stat /root/.bootstrapped
  register: need_bootstrap
  ignore_errors: true
  changed_when: false

- when: need_bootstrap is failed
  block:
    - name: Disable selinux
      selinux:
        state: disabled

    - name: Stop and disable firewalld.
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install required cluster packages
      yum: state=present name={{ item }}
      with_items:
        - epel-release
        - docker
        - python-docker-py

    - service:
        name: docker
        enabled: yes

    - name: Set bootstrapped file
      file:
        path: /root/.bootstrapped
        state: touch

    - name: restart machine
      shell: nohup sh -c '(sleep 5; shutdown -r now "Ansible restart") &' &>/dev/null

    - name: wait for the system to reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 60
