- name: Prepare inventory
  hosts: ansible_runner
  gather_facts: no
  tasks:
  - name: Template hosts
    copy:
      content: |
          [starter]
          {{ starter_host }}

          [masters:children]

          [etcd:children]
          masters

          [nodes:children]
          masters

          [OSEv3:children]
          masters
          nodes

          [glusterfs:children]
          nodes

      dest: '{{ inventory_dir}}/home_cluster_hosts'
    run_once: yes

  - meta: refresh_inventory

  - debug:
      var: groups.all
